piVersion: apps/v1
kind: Deployment
metadata:
  name: nginx01
  namespace: development
spec:
  selector:
    matchLabels:
      run: nginx01
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx01
    spec:
      containers:
      - name: nginx01
        image: nginx
        ports:
        - containerPort: 80
